require('colepeters/plugins')
require('colepeters/options')
require('colepeters/keymaps')
require('colepeters/diagnostic')
require('colepeters/plugins/autopairs')
require('colepeters/plugins/indentBlankline')
require('colepeters/plugins/mason')
require('colepeters/plugins/nightfox')
require('colepeters/plugins/nvim-cmp')
require('colepeters/plugins/telescope')
require('colepeters/plugins/treesitter')

